### ISSUE TITLE
Error on dataset(RNDTv.2)-featureCatalogue linking

### ISSUE THREAD

**Issue by mbeneventi** [metadata101/iso19139.rndt#12]
When I try to link a dataset (RNDTv.2 model) to a featureCatalogue (ISO19110) system return to me the following error:

![errore](https://user-images.githubusercontent.com/34231652/129015563-f7793385-58c8-41b0-af7e-7b205c086188.png)

**XML response**
```
<apiError>
  <code>runtime_exception</code>
  <description>Not found:0, Not owner:0, No process found:1. is not a valid value for: Processing failed</description>
  <message>BadParameterEx</message>
</apiError>
```

Whene I try to link a dataset ( Template for Vector data in ISO19139 (preferred! model) to the same featureCatalogue (ISO19110) everything working fine:

1. table "relations" is not populated
2. in the dataset XML we have a new TAG:

```
<gmd:contentInfo>
      <gmd:MD_FeatureCatalogueDescription>
         <gmd:includedWithDataset/>
         <gmd:featureCatalogueCitation uuidref="32bcd135-185f-4b20-80a3-ffe4c65eee5f" 
		                               xlink:href="http://localhost:8080/geonetwork/srv/ita/csw?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;id=32bcd135-185f-4b20-80a3-ffe4c65eee5f"/>
      </gmd:MD_FeatureCatalogueDescription>
   </gmd:contentInfo>
```

**Comment by etj** [comment]
Closed with #35
