### ISSUE TITLE
URI of INSPIRE themes thesaurus

### ISSUE THREAD

**Issue by etj** [metadata101/iso19139.rndt#29]
The official URI of the "GEMET - INSPIRE themes, version 1.0" thesaurus, as downloaded from the INSPIRE registry, is "http://inspire.ec.europa.eu/theme" while RNDT requires it to be set to "http://www.eionet.europa.eu/gemet/inspire_themes".

At the moment there's a batch process that converts the URI in the metadata:
![image](https://user-images.githubusercontent.com/717359/179632160-51ee6866-00b5-43ab-8375-9b34f3842c36.png)
but the newly edited/added metadata will still refer the INPIRE official URI.

**Comment by etj** [comment]
As per the resolution for #25 we may want to:
- have the correct URI when creating / editing the metadata
- correct the URI on the fly in CSW responses, in order not to have to edit and fix all the metadata documents (pls also consider using the batch process described in this issue main description).

**Comment by SaraRatto** [comment]
Hi, we have verified with RNDT and it's possibile to use both the URL and there will be non problems for the validation. Possibly they will also add a note in RNDT technical rules.
