### ISSUE TITLE
Metadata editing form is corrupted after the installation of the plugin

### ISSUE THREAD

**Issue by pdorio** [metadata101/iso19139.rndt#3]
To reproduce the problem:

1. Start with a clean installation of GN 3.4 or 3.6 for example using docker

`docker run --name geonetwork-3.4 -d -p 8080:8080 -e DATA_DIR=/var/lib/geonetwork_data -v /host/geonetwork-docker:/var/lib/geonetwork_data /var/run/docker.sock:/var/run/docker.sock geonetwork:3.4.0`

2. Import a new record from XML, for example: [ortofoto_merano_3.4.zip](https://github.com/metadata101/iso19139.rndt/files/3172633/ortofoto_merano_3.4.zip)

3. Install the plugin by copying the [plugin folder]() in the geonetwork directory

`cp -r src/main/plugin/iso19139.rndt /host/geonetwork-docker/config/schema_plugins/.`

4. Restart the container
`docker restart geonetwork-3.4`

5. Select and load the RNDT plugin models

5. Export the imported record
6. Re-import the exported record.

After the new import, the editing screen loose the section on the right (overview, validations and suggestions) making it unusable.
The choice is only "Base" and "XML" but in some cases even breaks the XML editing screen 

The dataset in editing mode before loading the plugin

![ok](https://user-images.githubusercontent.com/3297563/57619454-45492600-7586-11e9-9e5d-3167be3cc3e9.png)

The same dataset in editing mode imported after loading the plugin

![corrupted](https://user-images.githubusercontent.com/3297563/57619459-48441680-7586-11e9-9f8c-65f4ec61afe3.png)

**Comment by pdorio** [comment]
@davidegiacomelli avrei bisogno di alcuni consigli. Ti pregherei di contattarmi all'indirizzo pietro.dorio@siag.it

**Comment by SaraRatto** [comment]
Hi,
it is possible to restore the SidePanel (Validation, etc) adding this part in the configuration of the view (there is just the default one):
<sidePanel>
        <directive data-gn-onlinesrc-list=""/>
        <directive gn-geo-publisher=""
                   data-ng-if="gnCurrentEdit.geoPublisherConfig"
                   data-config="{{gnCurrentEdit.geoPublisherConfig}}"
                   data-lang="lang"/>
        <directive data-gn-validation-report=""/>
        <directive data-gn-suggestion-list=""/>
        <directive data-gn-need-help="user-guide/describing-information/creating-metadata.html"/>
      </sidePanel>
in the [config-editor.xml](https://github.com/metadata101/iso19139.rndt/blob/master/src/main/plugin/iso19139.rndt/layout/config-editor.xml). of the plugin. We just copy the code from the same type of file in the ISO 101139 plugin. 
It's not the perfect solution but it works and gives you the possibility to test the RNDT Validation.

**Comment by pdorio** [comment]
Thank you very much Sara!
It works great!!!
