### ISSUE TITLE
any hints on having this working with current GeoNetwork master branch?

### ISSUE THREAD

**Issue by mov-q** [metadata101/iso19139.rndt#9]
Hi, i tried to use this plugin with current GeoNetwork git master branch, adding it as a module and rebuilding everything according to general schema plugin instructions. i am having a hard time to get it working fine, as it seems the plugin somewhat conflicts with something in the iso19139 schema (duplicate named template xsl errors). More: i try to change the editor layout to introduce a sidepanel allowing me to attach file resources, but found no easy way to have this working too. 

any hints? thanks in advance for your support

**Comment by etj** [comment]
Version tagged [rndt1_PAT](https://github.com/metadata101/iso19139.rndt/tree/rndt1_PAT) was not maintained by the author.

You may want to check current master or version tagged [v1.0](https://github.com/metadata101/iso19139.rndt/releases/tag/v1.0) for GN compatibility with GN3.10.x (no test against 4.x have been performed tho).
